name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update r0x0d repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in my blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "BLOG"
          feed_list: "https://r0x0d.github.io/blog/feed.xml"
      
  update-readme-with-talks:
    name: Update r0x0d repo's README with latest talks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in my blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "TALKS"
          feed_list: "https://r0x0d.github.io/talks/feed/slides.xml"
